### ISSUE TITLE
Incorrect enharmonic spellings for chord / scale notes

### ISSUE THREAD

**Issue by taearls** [ozankasikci/rust-music-theory#32]
Hi everyone! This project looks neat. I'm noticing in the examples, however, that the enharmonic spellings for the note names are incorrect. For example, 

`rustmt scale D Locrian`
is shown with this output:
Notes:
  1: D
  2: D#
  3: F
  4: G
  5: G#
  6: A#
  7: C
  8: D
  
 But it should be notated as follows:
 1. D
 2. Eb
 3. F
 4. G
 5. Ab
 6. Bb
 7. C
 8. D
 
In other words, each letter name in a scale (and in chords) should be notated with the correct name relative to the interval.

**Comment by taearls** [comment]
Oh... I just saw that this issue is specified on your roadmap. Sorry all. I'll close this out.

**Comment by henryksloan** [comment]
Howdy! This is a known issue and priority. I think it's acknowledged in the README, and there are some standing Issues recommending solutions. My PR a while back has some initial support for enharmonics, so that would be a good start.

In respect to the definition of Diatonic scales, it might make sense to encode the fact that they contain one of each letter name (A-G). I don't exactly remember the present implementation, but we could probably start at the letter name of the root, and iterate up to the subtonic, choosing accidentals based on the scale definition.
