### ISSUE TITLE
It would be nice to have tab representation for the chords.

### ISSUE THREAD

**Issue by gorros** [ozankasikci/rust-music-theory#4]
As a guitar/bass player I would really appreciate to have also tab representation of the crods depending on root not string. 
I am new to rust but I would be glad to help.

**Comment by ozankasikci** [comment]
I would love to have this kind of functionality. I actually plan to develop a graphical UI and use this library as a backend. Then this could be an option. Otherwise printing tab representation of the chords/scales in the command line is not the most user friendly way to convey this kind of information.

**Comment by ozankasikci** [comment]
Closing this as we'll be planing a GUI application for the project!
